<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Marimo.SpreadSheetAsData.Build</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>Marimo.SpreadSheetAsData.Build</PackageId>
    <Version>0.2.3</Version>
    <Authors>HrmsTrsmgs</Authors>
    <Description>Provides MSBuild and Visual Studio integration for SpreadsheetAsData code generation.</Description>
    <PackageTags>excel;spreadsheet;openxml;msbuild;visual-studio;xlsx</PackageTags>
    <PackageProjectUrl>https://github.com/HrmsTrsmgs/SpreadsheetAsData</PackageProjectUrl>
    <RepositoryUrl>https://github.com/HrmsTrsmgs/SpreadsheetAsData</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);AddSpreadsheetAsDataBuildToolsToPackage</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpreadSheetAsData.CodeGeneration\SpreadSheetAsData.CodeGeneration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Build.Framework">
      <HintPath>$(MSBuildToolsPath)\Microsoft.Build.Framework.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Build.Utilities.Core">
      <HintPath>$(MSBuildToolsPath)\Microsoft.Build.Utilities.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" Visible="false" />
    <None Include="buildTransitive\Marimo.SpreadSheetAsData.Build.props" Pack="true" PackagePath="buildTransitive\Marimo.SpreadSheetAsData.Build.props" Visible="false" />
    <None Include="buildTransitive\Marimo.SpreadSheetAsData.Build.targets" Pack="true" PackagePath="buildTransitive\Marimo.SpreadSheetAsData.Build.targets" Visible="false" />
    <None Include="PackagePlaceholder\_._" Pack="true" PackagePath="lib\net10.0\_._" Visible="false" />
  </ItemGroup>

  <Target
    Name="AddSpreadsheetAsDataBuildToolsToPackage"
    Returns="@(TfmSpecificPackageFile)">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(TargetDir)**\*.*">
        <PackagePath>tools\net10.0\%(RecursiveDir)%(Filename)%(Extension)</PackagePath>
      </TfmSpecificPackageFile>
    </ItemGroup>
  </Target>

</Project>
